INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (1,  'French Bulldog', '$2000-$4000', '10-12', 'Playful, Socialble, Lively, Patient', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (2,  'Labrador Retriever', '$800-$1500','10-12', 'Cheerfull, Gentle, Friendly, Intelligent', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (3,  'Golden Retriever','$1000-$2000','10-12','Intelligent, Kind, Friendly, Confident', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (4,  'German Shepherd', '$800-$2000', '10-13', 'Courageous, Intelligent, Loyal, Watchful', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (5,  'Poodle', '$1200-$2500', '12-15', 'Intelligent, Faithful, Trainable, Instinctual', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (6,  'Bulldog', '$2000-$4000', '8-10', 'Friendly, Docile, Willful, Gregarious', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (7,  'Rottweiler', '$1200-$2000', '8-11', 'Intelligent, Courageous, Fearless, Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (8,  'Beagle', '$800-$1500', '12-15', 'Gentle, Intelligent, Even Tempered, Determined', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (9,  'Daschhund', '$800-$1500', '12-15', 'Clever, Courageous, Devoted, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (10, 'German Shorthaired Pointer', '$800-$1500','12-14', 'Intelligent, Trainable, Boisterous, Cooperative', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (11, 'Pembroke Welsh Corgi', '$1000-$2000', '12-13', 'Intelligent, Playful, Outgoing, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (12, 'Australian Shepherd', '$1000-$2000', '12-15', 'Active, Intelligent, Good-Natured, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (13, 'Yorkshire Terrier', '$1500-$3000', '12-16', 'Independant, Intelligent, Courageous, Confident', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (14, 'Cavalier King Charles Spaniel', '$1500-$2500', '10-14', 'Playful, Sociable, Patient, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (15, 'Doberman Pinscher', '$1200-$2500', '10-12', 'Intelligent, Obedient, Loyal, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (16, 'Boxer', '$1000-$2000', '10-12', 'Playful, Friendly, Devoted, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (17, 'Miniature Schnauzer', '$1200-$2500', '12-14', 'Intelligent, Friendly, Obedient, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (18, 'Cane Corso', '$1500-$2500', '10-11', 'Quiet, Even Tempered, Calm, Reserved', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (19, 'Great Dane', '$1000-$2000', '7-10', 'Gentle, Friendly, Devoted, Reserved', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (20, 'Shih TZu', '$1000-$1800', '10-16', 'Happy, Playful, Gentle, Friendly', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (21, 'Siberian Husky', '$600-$1300', '12-14', 'Gentle, Intelligent, Outgoing, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (22, 'Bernese Mountain Dog', '$1500-$3000','7-10', 'Affectionate, Intelligent, Loyal, Faithful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (23, 'Pomeranian', '$1500-$3000', '12-16', 'Playful, Intelligent, Sociable, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (24, 'Boston Terrier', '$1000-$2000', '12-15', 'Intelligent, Friendly, Lively, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (25, 'Havanese', '$1500-$2500', '14-16', 'Companionable, Responsive, Playful, Affectionate', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (26, 'English Springer Spaniel', '$800-$1800', '10-14', 'Attentive, Intelligent, Active, Cheerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (27, 'Shetland Sheepdog', '$1000-$2000', '12-14', 'Playful, Gentle, Intelligent, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (28, 'American Cocker Spaniel', '$1000-$2000', '12-15', 'Outgoing, Sociable, Even Tempered, Trusting', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (29, 'Brittany', '$700-$1100', '12-15', 'Happy, Intelligent, Agile, Quick', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (30, 'Border Collie', '$800-$1500', '12-15', 'Intelligent, Energetic, Tenacious, Responsive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (31, 'Miniature American Shepherd', '$800-$1500', '13-15','Energetic, Intelligent, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (32, 'Belgian Malinois', '$1000-$1800', '12-14', 'Stubborn, Confident, Protective, Watchful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (33, 'Vizsla', '$1000-$1800', '10-14', 'Intelligent, Loyal, Affectionate, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (34, 'Chihuahua', '$800-$2500', '14-18', 'Devoted, Quick, Courageous, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (35, 'Pug', '$800-$1500', '12-15', 'Playful, Stubborn, Attentive, Sociable','False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (36, 'Basset Hound', '$800-1500', '10-12', 'Gentle, Friendly, Devoted, Sweet-Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (37, 'Mastiff', '$1000-$2000', '10-12', 'Dignified, Affectionate, Good-Natured, Courageous', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (38, 'Maltese', '$1500-$2500', '15-18', 'Playful, Gentle, Lively, Docile', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (39, 'Collie', '$1200-$1800', '14-16', 'Gentle, Loyal, Intelligent, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (40, 'English Cocker Spaniel', '$1000-$1800', '12-14', 'Playful, Faithful, Friendly, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (41, 'Rhodesian Ridgeback', '$1000-$2000', '10-12','Dignified, Sensitive, Mischievous, Strong Willed', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (42, 'Newfoundland', '$1700-$2500', '9-12', 'Gentle, Trainable, Sweet-Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (43, 'Shiba Inu', '$1500-$2500', '12-15', 'Charming, Confident, Fearless, Keen', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (44, 'Weimaraner', '$700-$1500', '10-12', 'Energetic, Stubborn, Fast, Intelligent', 'Fasle');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (45, 'West Highland White Terrier','$1500-$3000', '12-16', 'Hardy, Friendly, Independent, Courageous', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (46, 'Portuguese Water Dog', '$2000-$3000', '10-14', 'Brave, Quarrelsome, Docile, Impetuous', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (47, 'Bichon Frise', '$1000-$2000', '12-15', 'Playful, Gentle, Sensitive,Cheerful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (48, 'Australian Cattle Dog', '$400-$1000', '12-15', 'Intelligent, Loyal, Energetic, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (49, 'Dalmatian', '$1000-$1600', '12-14', 'Intelligent, Outgoing, Friendly, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (50, 'Bloodhound', '$700-$1200', '10-12', 'Stubborn, Affectionate, Gentle, Even Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (51, 'Papillon', '$1000-$2000', '13-16', 'Friendly, Energetic, Happy, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (52, 'Chesapeake Bay Retriever', '$800-$1500', '10-13', 'Happy, Affectionate, Intelligent, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (53, 'Samoyed', '$1500-$3000', '12-14', 'Lively, Sociable, Friendly, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (54, 'Whippet', '$2000-$2500', '12-15', 'Gentle, Affectionate, Intelligent, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (55, 'Akita', '$1000-$2500', '10-14', 'Dignified, Friendly, Courageous, Docile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (56, 'St. Bernard', '$1000-$2000', '8-10', 'Friendly, Lively, Watchful, Gentle', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (57, 'Wirehaired Pointing Griffon', '$1000-$2000', '12-14', 'Loyal, Trainable,Gentle, Vigilant', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (58, 'Giant Schnauzer', '$2000-$3000', '10-12', 'Kind, Strong Willed, Powerful, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (59, 'German Wirehaired Pointer', '$800-$1200', '12-14', 'Willful, Intelligent, Affectionate, Active', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (60, 'Scottish Terrier', '$1400-$2000', '11-13', 'Quick, Independent, Self-Assured, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (61, 'Bullmastiff', '$1500-$2500', '8-10', 'Courageous, Docile, Loyal, Powerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (62, 'Cardigan Welsh Corgi', '$1200-$2200', '12-15', 'Intelligent, Alert, Devoted, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (63, 'Italian Greyhound', '$1400-$2000', '12-15', 'Intelligent, Agile, Athletic, Companionable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (64, 'Bull Terrier', '$1200-$2000', '10-12', 'Sweet-Tempered, Keen, Protective, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (65, 'Shar-Pei', '$1000-$1500', '9-11', 'Independent, Reserved, Suspicious, Devoted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (66, 'Airedale Terrier', '$800-$1500', '10-13', 'Intelligent, Outgoing, Courageous, Confident', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (67, 'Soft Coated Wheaten Terrier', '$1800-$3000', '12-15', 'Spirited, Faithful, Energetic, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (68, 'Alaskan Malamute', '$1200-$2000', '12-15', 'Dignified, Playful, Friendly, Devoted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (69, 'Great Pyrenees', '$800-$1500', '10-12', 'Patient, Affectionate, Confident, Strong Willed', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (70, 'Cairn Terrier', '$1200-$2000', '12-15', 'Intelligent, Fearless, Hardy, Assertive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (71, 'Irish Setter', '$1200-$2500', '12-14', 'Intelligent, Lively, Playful, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (72, 'Miniature Pinscher', '$1000-$2000', '12-15', 'Playful, Outgoing, Energetic, Responsive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (73, 'Jack Russell Terrier', '$800-$1500', '13-16', 'Vocal, Stubborn, Athletic, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (74, 'Old English, Sheepdog', '$1800-$3000', '10-12', 'Bubbly, Intelligent, Adaptable, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (75, 'Staffordshire Bull Terrier', '$1500-$2500', '12-14', 'Reliable, Courageous, Affectionate, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (76, 'Lagotto Romagnolo', '$3000-$5000', '14-16', 'Loving, Loyal, Companionable, Trainable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (77, 'Biewer Terrier', '$2500-$4500', '12-16', ' Active, Devoted, Intelligent, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (78, 'Dogue de Bordeaux', '$1800-$2500', '10-12', 'Devoted, Courageous, Companionable, Vigilant', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (79, 'Anatolian Shepherd Dog', '$800-$1200', '10-13', 'Independent, Steady, Confident, Proud', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (80, 'Chinese Crested', '$1000-$2000', '12-14', 'Happy, Playful, Affectionate, Sweet-Tempered', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (81, 'Nova Scotia Duck Tolling Retriever', '$1500-$2500', '12-14', 'Outgoing, Loving, Alert, Patient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (82, 'Boykin Spaniel', '$700-$1200', '14-16', 'Friendly, Energetic, Companionable, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (83, 'Greater Swiss Mountain Dog', '$1200-$2800', '10-12', 'Protective, Self-Confident, Devoted, Good-Natured', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (84, 'Coton De Tulear', '$1500-$2500', '14-16', 'Playful, Affectionate, Lively, Trainable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (85, 'Rat Terrier', '$600-$1200', '15-18', 'Loving, Alert, Lively, Inquisitive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (86, 'Lhasa Apso', '$1500-$2500', '12-15', 'Energetic, Playful, Intelligent, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (87, 'American Staffordshire Terrier', '$1500-$2500', '12-14', 'Friendly, Devoted,Courageous, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (88, 'Dogo Argentino', '$1500-$2500', '10-12', 'Friendly, Loyal, Protective, Cheerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (89, 'Irish Wolfhound', '$1500-$2500', '6-10', 'Dignified, Generous, Loyal, Patient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (90, 'Keeshond', '$1500-$2000', '12-14', 'Intelligent, Quick, Agile, Sturdy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (91, 'Basenji', '$1500-$2000', '12-15', 'Curious, Affectionate, Intelligent, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (92, 'Chow Chow', '$1200-$2000', '13-15', 'Aloof, Independent, Loyal, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (93, 'English Setter', '$1000-$1500', '10-12', 'Intelligent, Energetic, Mischievous, Strong Willed', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (94, 'Standard Schnauzer', '$1500-$2500', '12-15', 'Lively, Trainable, Intelligent, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (95, 'Border Terrier', '$800-$1500', '12-15', 'Intelligent, Obedient, Even Tempered, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (96, 'Pekingese', '$1500-$3000', '13-15', 'Stubborn, Opinionated, Aggressive, Good-Natured', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (97, 'Brussels Griffon', '$1800-$2800', '12-15', 'Companionable, Sensitive, Watchful, Inquisitive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (98, 'Bouvier des Flandres', '$1500-$2500', '10-12', 'Intelligent, Loyal, Protective, Familial', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (99, 'Gordon Setter', '$1000-$2000', '10-12', 'Intelligent, Confident, Alert, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (100, 'Norwegian Elkhound', '$700-$1500', '10-12', 'Strong Willed, Hardy, Intelligent, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (101, 'Borzoi', '$1500-$3000', '10-12', 'Gentle, Independent, Quiet, Athletic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (102, 'Wire Fox Terrier', '$1500-$3000', '12-14', 'Quick, Keen, Friendly, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (103, 'Flat-Coated Retriever', '$1500-$3000', '10-13', 'Optimistic, Outgoing, Devoted, Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (104, 'Belgian Tervuren', '$1500-$2000', '10-12', 'Intelligent, Loyal, Energetic, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (105, 'Japanese Chin', '$1500-$2500', 'Loving, Cat-Like, Loyal, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (106, 'Tibetan Terrier', '$1500-$2500', '12-15', 'Energetic, Sensitive, Reserved, Amiable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (107, 'Pointer', '$1000-$1500', '12-15', 'Even Tempered, Amiable, Loyal, Kind', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (108, 'Toy Fox Terrier', '$1000-$1800', '13-14', 'Spirited, Friendly, Playful, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (109, 'Norwich Terrier', '$2000-$4000', '12-15', 'Sensitive, Intelligent, Hardy, Energetic', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (110, 'Miniature Bull Terrier', '$2500-$3500', '10-12', 'Playful, Energetic, Even Tempered, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (111, 'Beauceron', '$2000-$2500', '10-12', 'Friendly, Calm, Fearless, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (112, 'Spinone Italiano', '$1200-$2000', '12-14','Patient, Loyal, Gentle, Docile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (113, 'Welsh Terrier', '$1500-$3000', '10-14', 'Spirited, Alert, Intelligent, Friendly', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (114, 'Leonberger', '$2000-$4000', '8-10', 'Loyal, Companionable, Fearless, Obedient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (115, 'Schipperke', '$1200-$2000', '13-15', 'Confident, Fearless, Faithful, Agile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (116, 'Xoloitzcuintli', '$2000-$4000', '14-20', 'Companionable, Protective, Intelligent, Cheerful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (117, 'Afghan Hound', '$2500-$3500', '12-14', 'Clownish, Happy, Dignified, Independent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (118, 'Boerboel', '$2000-$4000', '10-12', 'Obedient, Dominant, Confident, Territorial', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (119, 'Neapolitan Mastiff', '$2500-$4500', '9-10', 'Obedient, Stubborn, Dominant, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (120, 'American Hairless Terrier', '$2000-$4000', '14-16', 'Playful, Alert, Lively, Inquisitve', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (121, 'Parson Russel Terrier', '$1200-$2000', '13-15', 'Happy, Obedient, Energetic, Eager', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (122, 'Silky Terrier', '$1000-$2000', '12-15', 'Friendly, Quick, Responsive, Inquisitive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (123, 'American Eskimo Dog', '$1000-$2000', '12-15', 'Alert, Friendly, Reserved, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (124, 'Bearded Collie', '$1500-$2000', '12-14', 'Intelligent, Lively, Hardy, Self-Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (125, 'Belgian Sheepdog','$1500-$3000', '12-14', 'Powerful, Dominant, Loyal, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (126, 'Welsh Springer Spaniel', '$2000-$2500','12-15', 'Friendly, Loyal, Stubborn, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (127, 'Tibetan Spaniel', '$1500-$2000','12-15', 'Willful, Assertive, Intelligent, Aloof', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (128, 'Black Russian Terrier', '$3000-$4000', '10-14','Lively, Energetic, Confident, Hardy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (129, 'Greyhound', '$1500-$2500', '10-13', 'Athletic, Even Tempered, Gentle, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (130, 'Manchester Terrier', '$500-$1000', '14-16', 'Devoted, Active, Alert, Discerning', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (131, 'Irish Terrier', '$1500-$2500', '12-15', 'Respectful, Dominant, Protective, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (132, 'Icelandic, Sheepdog', '$1000-$1500', '12-15', 'Energetic, Cheerful, Inquisitive, Hardy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (133, 'Bluetick Coonhound', '$400-$1200', '11-12', 'Active, Intelligent, Friendly, Gentle', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (134, 'English Toy Spaniel', '$2000-$2500', '10-12', 'Loyal, Playful, Quiet, Social', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (135, 'Saluki', '$2500-$3000', '12-14', 'Reserved, Aloof, Quiet, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (136, 'Australian Terrier', '$1200-$1500','12-15', 'Courageous, Loyal, Even Tempered, Companionable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (137, 'Tibetan Mastiff', '$2500-$4000', '10-14', 'Stubborn, Tenacious, Strong Willed, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (138, 'Norfolk Terrier', '$2500-$3500', '12-15', 'Self-Confident, Spirited, Loveable, Happy', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (139, 'Clumber Spaniel', '$1200-$1500', '10-12', 'Dignified, Gentle, Loyal, Great-Hearted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (140, 'Pumi', '$2000-$3000', '12-15', 'Protective, Reserved, Vocal, Lively', 'False');
