INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (1,  'French Bulldog', '$2000-$4000', '10-12', 'Playful, Socialble, Lively, Patient', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (2,  'Labrador Retriever', '$800-$1500','10-12', 'Cheerfull, Gentle, Friendly, Intelligent', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (3,  'Golden Retriever','$1000-$2000','10-12','Intelligent, Kind, Friendly, Confident', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (4,  'German Shepherd', '$800-$2000', '10-13', 'Courageous, Intelligent, Loyal, Watchful', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (5,  'Poodle', '$1200-$2500', '12-15', 'Intelligent, Faithful, Trainable, Instinctual', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (6,  'Bulldog', '$2000-$4000', '8-10', 'Friendly, Docile, Willful, Gregarious', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (7,  'Rottweiler', '$1200-$2000', '8-11', 'Intelligent, Courageous, Fearless, Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (8,  'Beagle', '$800-$1500', '12-15', 'Gentle, Intelligent, Even Tempered, Determined', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (9,  'Daschhund', '$800-$1500', '12-15', 'Clever, Courageous, Devoted, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (10, 'German Shorthaired Pointer', '$800-$1500','12-14', 'Intelligent, Trainable, Boisterous, Cooperative', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (11, 'Pembroke Welsh Corgi', '$1000-$2000', '12-13', 'Intelligent, Playful, Outgoing, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (12, 'Australian Shepherd', '$1000-$2000', '12-15', 'Active, Intelligent, Good-Natured, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (13, 'Yorkshire Terrier', '$1500-$3000', '12-16', 'Independant, Intelligent, Courageous, Confident', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (14, 'Cavalier King Charles Spaniel', '$1500-$2500', '10-14', 'Playful, Sociable, Patient, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (15, 'Doberman Pinscher', '$1200-$2500', '10-12', 'Intelligent, Obedient, Loyal, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (16, 'Boxer', '$1000-$2000', '10-12', 'Playful, Friendly, Devoted, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (17, 'Miniature Schnauzer', '$1200-$2500', '12-14', 'Intelligent, Friendly, Obedient, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (18, 'Cane Corso', '$1500-$2500', '10-11', 'Quiet, Even Tempered, Calm, Reserved', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (19, 'Great Dane', '$1000-$2000', '7-10', 'Gentle, Friendly, Devoted, Reserved', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (20, 'Shih TZu', '$1000-$1800', '10-16', 'Happy, Playful, Gentle, Friendly', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (21, 'Siberian Husky', '$600-$1300', '12-14', 'Gentle, Intelligent, Outgoing, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (22, 'Bernese Mountain Dog', '$1500-$3000','7-10', 'Affectionate, Intelligent, Loyal, Faithful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (23, 'Pomeranian', '$1500-$3000', '12-16', 'Playful, Intelligent, Sociable, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (24, 'Boston Terrier', '$1000-$2000', '12-15', 'Intelligent, Friendly, Lively, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (25, 'Havanese', '$1500-$2500', '14-16', 'Companionable, Responsive, Playful, Affectionate', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (26, 'English Springer Spaniel', '$800-$1800', '10-14', 'Attentive, Intelligent, Active, Cheerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (27, 'Shetland Sheepdog', '$1000-$2000', '12-14', 'Playful, Gentle, Intelligent, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (28, 'American Cocker Spaniel', '$1000-$2000', '12-15', 'Outgoing, Sociable, Even Tempered, Trusting', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (29, 'Brittany', '$700-$1100', '12-15', 'Happy, Intelligent, Agile, Quick', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (30, 'Border Collie', '$800-$1500', '12-15', 'Intelligent, Energetic, Tenacious, Responsive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (31, 'Miniature American Shepherd', '$800-$1500', '13-15','Energetic, Intelligent, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (32, 'Belgian Malinois', '$1000-$1800', '12-14', 'Stubborn, Confident, Protective, Watchful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (33, 'Vizsla', '$1000-$1800', '10-14', 'Intelligent, Loyal, Affectionate, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (34, 'Chihuahua', '$800-$2500', '14-18', 'Devoted, Quick, Courageous, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (35, 'Pug', '$800-$1500', '12-15', 'Playful, Stubborn, Attentive, Sociable','False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (36, 'Basset Hound', '$800-1500', '10-12', 'Gentle, Friendly, Devoted, Sweet-Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (37, 'Mastiff', '$1000-$2000', '10-12', 'Dignified, Affectionate, Good-Natured, Courageous', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (38, 'Maltese', '$1500-$2500', '15-18', 'Playful, Gentle, Lively, Docile', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (39, 'Collie', '$1200-$1800', '14-16', 'Gentle, Loyal, Intelligent, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (40, 'English Cocker Spaniel', '$1000-$1800', '12-14', 'Playful, Faithful, Friendly, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (41, 'Rhodesian Ridgeback', '$1000-$2000', '10-12','Dignified, Sensitive, Mischievous, Strong Willed', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (42, 'Newfoundland', '$1700-$2500', '9-12', 'Gentle, Trainable, Sweet-Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (43, 'Shiba Inu', '$1500-$2500', '12-15', 'Charming, Confident, Fearless, Keen', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (44, 'Weimaraner', '$700-$1500', '10-12', 'Energetic, Stubborn, Fast, Intelligent', 'Fasle');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (45, 'West Highland White Terrier','$1500-$3000', '12-16', 'Hardy, Friendly, Independent, Courageous', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (46, 'Portuguese Water Dog', '$2000-$3000', '10-14', 'Brave, Quarrelsome, Docile, Impetuous', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (47, 'Bichon Frise', '$1000-$2000', '12-15', 'Playful, Gentle, Sensitive,Cheerful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (48, 'Australian Cattle Dog', '$400-$1000', '12-15', 'Intelligent, Loyal, Energetic, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (49, 'Dalmatian', '$1000-$1600', '12-14', 'Intelligent, Outgoing, Friendly, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (50, 'Bloodhound', '$700-$1200', '10-12', 'Stubborn, Affectionate, Gentle, Even Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (51, 'Papillon', '$1000-$2000', '13-16', 'Friendly, Energetic, Happy, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (52, 'Chesapeake Bay Retriever', '$800-$1500', '10-13', 'Happy, Affectionate, Intelligent, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (53, 'Samoyed', '$1500-$3000', '12-14', 'Lively, Sociable, Friendly, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (54, 'Whippet', '$2000-$2500', '12-15', 'Gentle, Affectionate, Intelligent, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (55, 'Akita', '$1000-$2500', '10-14', 'Dignified, Friendly, Courageous, Docile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (56, 'St. Bernard', '$1000-$2000', '8-10', 'Friendly, Lively, Watchful, Gentle', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (57, 'Wirehaired Pointing Griffon', '$1000-$2000', '12-14', 'Loyal, Trainable,Gentle, Vigilant', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (58, 'Giant Schnauzer', '$2000-$3000', '10-12', 'Kind, Strong Willed, Powerful, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (59, 'German Wirehaired Pointer', '$800-$1200', '12-14', 'Willful, Intelligent, Affectionate, Active', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (60, 'Scottish Terrier', '$1400-$2000', '11-13', 'Quick, Independent, Self-Assured, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (61, 'Bullmastiff', '$1500-$2500', '8-10', 'Courageous, Docile, Loyal, Powerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (62, 'Cardigan Welsh Corgi', '$1200-$2200', '12-15', 'Intelligent, Alert, Devoted, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (63, 'Italian Greyhound', '$1400-$2000', '12-15', 'Intelligent, Agile, Athletic, Companionable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (64, 'Bull Terrier', '$1200-$2000', '10-12', 'Sweet-Tempered, Keen, Protective, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (65, 'Shar-Pei', '$1000-$1500', '9-11', 'Independent, Reserved, Suspicious, Devoted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (66, 'Airedale Terrier', '$800-$1500', '10-13', 'Intelligent, Outgoing, Courageous, Confident', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (67, 'Soft Coated Wheaten Terrier', '$1800-$3000', '12-15', 'Spirited, Faithful, Energetic, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (68, 'Alaskan Malamute', '$1200-$2000', '12-15', 'Dignified, Playful, Friendly, Devoted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (69, 'Great Pyrenees', '$800-$1500', '10-12', 'Patient, Affectionate, Confident, Strong Willed', 'false');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (70, 'Cairn Terrier', '$1200-$2000', '12-15', 'Intelligent, Fearless, Hardy, Assertive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (71, 'Irish Setter', '$1200-$2500', '12-14', 'Intelligent, Lively, Playful, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (72, 'Miniature Pinscher', '$1000-$2000', '12-15', 'Playful, Outgoing, Energetic, Responsive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (73, 'Jack Russell Terrier', '$800-$1500', '13-16', 'Vocal, Stubborn, Athletic, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (74, 'Old English, Sheepdog', '$1800-$3000', '10-12', 'Bubbly, Intelligent, Adaptable, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (75, 'Staffordshire Bull Terrier', '$1500-$2500', '12-14', 'Reliable, Courageous, Affectionate, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (76, 'Lagotto Romagnolo', '$3000-$5000', '14-16', 'Loving, Loyal, Companionable, Trainable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (77, 'Biewer Terrier', '$2500-$4500', '12-16', ' Active, Devoted, Intelligent, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (78, 'Dogue de Bordeaux', '$1800-$2500', '10-12', 'Devoted, Courageous, Companionable, Vigilant', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (79, 'Anatolian Shepherd Dog', '$800-$1200', '10-13', 'Independent, Steady, Confident, Proud', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (80, 'Chinese Crested', '$1000-$2000', '12-14', 'Happy, Playful, Affectionate, Sweet-Tempered', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (81, 'Nova Scotia Duck Tolling Retriever', '$1500-$2500', '12-14', 'Outgoing, Loving, Alert, Patient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (82, 'Boykin Spaniel', '$700-$1200', '14-16', 'Friendly, Energetic, Companionable, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (83, 'Greater Swiss Mountain Dog', '$1200-$2800', '10-12', 'Protective, Self-Confident, Devoted, Good-Natured', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (84, 'Coton De Tulear', '$1500-$2500', '14-16', 'Playful, Affectionate, Lively, Trainable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (85, 'Rat Terrier', '$600-$1200', '15-18', 'Loving, Alert, Lively, Inquisitive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (86, 'Lhasa Apso', '$1500-$2500', '12-15', 'Energetic, Playful, Intelligent, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (87, 'American Staffordshire Terrier', '$1500-$2500', '12-14', 'Friendly, Devoted,Courageous, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (88, 'Dogo Argentino', '$1500-$2500', '10-12', 'Friendly, Loyal, Protective, Cheerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (89, 'Irish Wolfhound', '$1500-$2500', '6-10', 'Dignified, Generous, Loyal, Patient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (90, 'Keeshond', '$1500-$2000', '12-14', 'Intelligent, Quick, Agile, Sturdy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (91, 'Basenji', '$1500-$2000', '12-15', 'Curious, Affectionate, Intelligent, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (92, 'Chow Chow', '$1200-$2000', '13-15', 'Aloof, Independent, Loyal, Quiet', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (93, 'English Setter', '$1000-$1500', '10-12', 'Intelligent, Energetic, Mischievous, Strong Willed', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (94, 'Standard Schnauzer', '$1500-$2500', '12-15', 'Lively, Trainable, Intelligent, Playful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (95, 'Border Terrier', '$800-$1500', '12-15', 'Intelligent, Obedient, Even Tempered, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (96, 'Pekingese', '$1500-$3000', '13-15', 'Stubborn, Opinionated, Aggressive, Good-Natured', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (97, 'Brussels Griffon', '$1800-$2800', '12-15', 'Companionable, Sensitive, Watchful, Inquisitive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (98, 'Bouvier des Flandres', '$1500-$2500', '10-12', 'Intelligent, Loyal, Protective, Familial', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (99, 'Gordon Setter', '$1000-$2000', '10-12', 'Intelligent, Confident, Alert, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (100, 'Norwegian Elkhound', '$700-$1500', '10-12', 'Strong Willed, Hardy, Intelligent, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (101, 'Borzoi', '$1500-$3000', '10-12', 'Gentle, Independent, Quiet, Athletic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (102, 'Wire Fox Terrier', '$1500-$3000', '12-14', 'Quick, Keen, Friendly, Fearless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (103, 'Flat-Coated Retriever', '$1500-$3000', '10-13', 'Optimistic, Outgoing, Devoted, Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (104, 'Belgian Tervuren', '$1500-$2000', '10-12', 'Intelligent, Loyal, Energetic, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (105, 'Japanese Chin', '$1500-$2500', '10-12','Loving, Cat-Like, Loyal, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (106, 'Tibetan Terrier', '$1500-$2500', '12-15', 'Energetic, Sensitive, Reserved, Amiable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (107, 'Pointer', '$1000-$1500', '12-15', 'Even Tempered, Amiable, Loyal, Kind', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (108, 'Toy Fox Terrier', '$1000-$1800', '13-14', 'Spirited, Friendly, Playful, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (109, 'Norwich Terrier', '$2000-$4000', '12-15', 'Sensitive, Intelligent, Hardy, Energetic', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (110, 'Miniature Bull Terrier', '$2500-$3500', '10-12', 'Playful, Energetic, Even Tempered, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (111, 'Beauceron', '$2000-$2500', '10-12', 'Friendly, Calm, Fearless, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (112, 'Spinone Italiano', '$1200-$2000', '12-14','Patient, Loyal, Gentle, Docile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (113, 'Welsh Terrier', '$1500-$3000', '10-14', 'Spirited, Alert, Intelligent, Friendly', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (114, 'Leonberger', '$2000-$4000', '8-10', 'Loyal, Companionable, Fearless, Obedient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (115, 'Schipperke', '$1200-$2000', '13-15', 'Confident, Fearless, Faithful, Agile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (116, 'Xoloitzcuintli', '$2000-$4000', '14-20', 'Companionable, Protective, Intelligent, Cheerful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (117, 'Afghan Hound', '$2500-$3500', '12-14', 'Clownish, Happy, Dignified, Independent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (118, 'Boerboel', '$2000-$4000', '10-12', 'Obedient, Dominant, Confident, Territorial', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (119, 'Neapolitan Mastiff', '$2500-$4500', '9-10', 'Obedient, Stubborn, Dominant, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (120, 'American Hairless Terrier', '$2000-$4000', '14-16', 'Playful, Alert, Lively, Inquisitve', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (121, 'Parson Russel Terrier', '$1200-$2000', '13-15', 'Happy, Obedient, Energetic, Eager', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (122, 'Silky Terrier', '$1000-$2000', '12-15', 'Friendly, Quick, Responsive, Inquisitive', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (123, 'American Eskimo Dog', '$1000-$2000', '12-15', 'Alert, Friendly, Reserved, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (124, 'Bearded Collie', '$1500-$2000', '12-14', 'Intelligent, Lively, Hardy, Self-Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (125, 'Belgian Sheepdog','$1500-$3000', '12-14', 'Powerful, Dominant, Loyal, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (126, 'Welsh Springer Spaniel', '$2000-$2500','12-15', 'Friendly, Loyal, Stubborn, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (127, 'Tibetan Spaniel', '$1500-$2000','12-15', 'Willful, Assertive, Intelligent, Aloof', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (128, 'Black Russian Terrier', '$3000-$4000', '10-14','Lively, Energetic, Confident, Hardy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (129, 'Greyhound', '$1500-$2500', '10-13', 'Athletic, Even Tempered, Gentle, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (130, 'Manchester Terrier', '$500-$1000', '14-16', 'Devoted, Active, Alert, Discerning', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (131, 'Irish Terrier', '$1500-$2500', '12-15', 'Respectful, Dominant, Protective, Intelligent', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (132, 'Icelandic, Sheepdog', '$1000-$1500', '12-15', 'Energetic, Cheerful, Inquisitive, Hardy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (133, 'Bluetick Coonhound', '$400-$1200', '11-12', 'Active, Intelligent, Friendly, Gentle', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (134, 'English Toy Spaniel', '$2000-$2500', '10-12', 'Loyal, Playful, Quiet, Social', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (135, 'Saluki', '$2500-$3000', '12-14', 'Reserved, Aloof, Quiet, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (136, 'Australian Terrier', '$1200-$1500','12-15', 'Courageous, Loyal, Even Tempered, Companionable', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (137, 'Tibetan Mastiff', '$2500-$4000', '10-14', 'Stubborn, Tenacious, Strong Willed, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (138, 'Norfolk Terrier', '$2500-$3500', '12-15', 'Self-Confident, Spirited, Loveable, Happy', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (139, 'Clumber Spaniel', '$1200-$1500', '10-12', 'Dignified, Gentle, Loyal, Great-Hearted', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (140, 'Pumi', '$2000-$3000', '12-15', 'Protective, Reserved, Vocal, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (141, 'Smooth Fox Terrier', '$1000-$2000', '12-15', 'Intelligent, Fearless, Playful, Active', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (142, 'Wirehaired Vizsla', '$1000-$1500', '12-14', 'Intelligent, Loyal, Out-Going, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (143, 'Lakeland Terrier', '$1500-$2800', '12-16', 'Independent, Trainable, Intelligent, Confident', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (144, 'Russian Toy', '$2000-$2500', '11-13', 'Active, Cheerful, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (145, 'German Pinscher', '$2000-$3000', '12-15', 'Even Tempered, Spirited, Lively, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (146, 'Kerry Blue Terrier', '$2000-$2500', '12-15', 'Spirited, Strong Willed, Gentle, Affectionate', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (147, 'Barbet', '$2500-$4000', '12-14', 'Intelligent, Obedient, Companionable, Joyful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (148, 'Affenpinscher', '$1800-$2500', '12-14', 'Adventurous, Fun-Loving, Playful, Stubborn', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (149, 'Black and Tan Coonhound', '$400-$800', '10-12', 'Gentle, Even Tempered, Easygoing, Lovable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (150, 'Mudi', '$2000-$2500', '12-14', 'Energetic, Lively, Keen, Courageous', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (151, 'Briard', '$1500-$3000', '10-12', 'Intelligent, Obedient, Faithful, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (152, 'Bedlington Terrier', '$1800-$2500', '14-16', 'Affectionate, Intelligent, Good-Tempered, Spirited', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (153, 'Berger Picard', '$2000-$2500', '12-15', 'Stubborn, Intelligent, Lively, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (154, 'Petit Basset Griffon Vendeen', '$1200-$1600', '11-14', 'Friendly, Independent, Lively, Active', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (155, 'Scottish Deerhound', '$1000-$2500', '8-10', 'Friendly, Docile, Dignified, Gentle', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (156, 'Curly-Coated Retriever', '$1500-$2500', '8-12', 'Intelligent, Clever, Independent, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (157, 'Field Spaniel', '$2000-$5000', '11-15','Sociable, Docile, Sensitive, Familial', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (158, 'Redbone Coonhound', '$500-$800','12-14', 'Familial, Energetic, Companionable, Unflappable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (159, 'Treeing Walker Coonhound', '$400-$800', '12-13', 'Loving, Affectionate, Clever, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (160, 'Swedish Vallhund', '$1500-$2300', '12-14','Friendly, Watchful, Fearless, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (161, 'Puli', '$1500-$2500', '12-16', 'Faithful, Energetic, Intelligent, Loyal', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (162, 'Entlebucher Mountain Dog', '$800-$1500', '10-15', 'Agile, Independent, Devoted, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (163, 'Spanish Water Dog', '$1500-$2500', '10-14', 'Diligent, Trainable, Loyal, Athletic', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (164, 'Sealyham Terrier', '$1500-$3000', '14-16', 'Friendly, Fearless, Even Tempered, Calm', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (165, 'Lowchen', '$4000-$8000', '12-15', 'Happy, Playful, Familial, Friendly', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (166, 'American Water Spaniel', '$1200-$1500', '10-13', 'Friendly, Devoted, Courageous, Tenacious', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (167, 'Finnish Lapphund', '$1000-$2000', '12-15', 'Friendly, Courageous, Faithful, Calm', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (168, 'Irish Red and White Setter', '$1800-$2500', '11-13', 'Reliable, Loyal, Energetic, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (169, 'Glen of Imaal Terrier', '$1500-$2200', '12-14', 'Agile, Spirited, Gentle, Active', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (170, 'Kooikerhondje', '$3000-$3500', '12-14', 'Territorial, Benevolent, Agile, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (171, 'Portuguese Podengo Pequeno', '$1000-$2500', '12-14', 'Friendly, Companionable, Active, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (172, 'Ibizan Hound', '$2000-$2500', '12-14', 'Engaging, Independent, Stubborn, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (173, 'Plott Hound', '$500-$700', '12-14', 'Intelligent, Loyal, Alert, Bold', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (174, 'Pharaoh Hound', '$1800-$2500', '12-14', 'Trainable, Sociable, Playful, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (175, 'Komondor', '$800-$1500', '10-12', 'Calm, Gently, Independent, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (176, 'Otterhound', '$1500-$2500', '10-12', 'Boisterous, Amiable, Even Tempered', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (177, 'Kuvasz', '$1500-$2500', '10-12', 'Patient, Clownish, Protective, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (178, 'Norwegian Buhund', '$2000-$2500', '13-15', 'Friendly, Fun-Loving, Energetic, Courageous', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (179, 'Bergamasco', '$1000-$2000', '13-15', 'Intelligent, Determined, Patient, Vigilant', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (180, 'Chinook', '$800-$1200', '12-15', 'Friendly, Calm, Dignified, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (181, 'Polish Lowland Sheepdog', '$2000-$2500', '10-12', 'Self-Confident, Perceptive, Lively, Even Tempered', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (182, 'American English Coonhound', '$800-$1200', '10-12', 'High-Strung, Intelligent, Loyal, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (183, 'Irish Water Spaniel', '$1500-$2000', '10-12', 'Intelligent, Inquisitive, Quick, Clownish', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (184, 'Cirneco dell´Etna', '$900-$1500', '12-15', 'Affectionate, Gentle, Friendly, Independent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (185, 'Grand Basset Griffon Vendeen', '$1200-$1500', '12-15', 'Stubborn, Fast, Alert, Courageous', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (186, 'Dandie Dinmont Terrier', '$1500-$3000', '12-14', 'Fun-Loving, Independent, Lively, Determined', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (187, 'Canaan Dog', '$1500-$2000', '12-14', 'Devoted, Quick, Cautious, Vigilant', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (188, 'Finnish Spitz', '$1000-$2000', '12-15', 'Vocal, Playful, Loyal, Intelligent', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (189, 'Skye Terrier', '$1500-$2000', '12-14', 'Friendly, Intelligent, Good-Tempered, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (190, 'Pyrenean Shepherd', '$800-$1200', '15-17', 'Energetic, Bossy, Watchful, Clever', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (191, 'Cesky Terrier', '$1200-$2500', '12-15', 'Quiet, Calm, Reserved, Cheerful', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (192, 'Sussex Spaniel', '$2000-$3000', '12-15', 'Sociable, Devoted, Calm, Cheerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (193, 'Harrier', '$1500-$2500', '10-12', 'Cheerful, Sweet-Tempered, Friendly, Social', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (194, 'Azawakh', '$2000-$2500', '10-12', 'Aloof, Fierce, Refined, Rugged', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (195, 'Belgian Shepherd Laekenois', '$1700-$2500', '10-12', 'Companionable, Sensitive, Watchful, Inquisitive', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (196, 'American Foxhound', '$500-$700', '10-12', 'Intelligent, Kind, Independent, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (197, 'Sloughi', '$1500-$2000', '12-15', 'Sensitive, Intelligent, Faithful, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (198, 'Norwegian Lundehund', '$2000-$3000', '10-12', 'Loyal, Protective, Alert, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (199, 'English Foxhound', '$600-$800', '10-13', 'Gentle, Sociable, Friendly, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (200, 'American Pit Bull Terrier', '$500-$1000', '10-14', 'Clownish, Stubborn, Affectionate, Obedient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (201, 'American White Shepherd', '$1000-$1500', '12-14', 'Companionable, Fearless, Eager, Self-Confident', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (202, 'Cockapoo', '$1000-$2000', '14-18', 'Active, Intelligent, Outgoing, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (203, 'Goldendoodle', '$1000-$2500', '10-15', 'Friendly, Trainable, Intelligent, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (204, 'Japanese Spitz', '$1000-$2500', '10-16', 'Proud, Companionable, Playful, Obedient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (205, 'Miniature Bulldog', '$1500-$4500', '9-12', 'Loving, Loyal, Active, Playful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (206, 'Volpino Italiano', '$700-$1500','14-16', 'Playful, Lively, Watchful, Affectionate', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (207, 'Bolognese dog', '$1000-$2500', '13-15', 'Playful, Easygoing, Earnest, Willing', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (208, 'Miniature Poodle', '$1500-$3000', '14-16', 'Intelligent, Faithful, Trainable, Instinctual', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (209, 'Toy Poodle', '$1500-$3000', '14-16', 'Intelligent, Faithful, Trainable, Instinctual', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (210, 'Miniature Shar Pei', '$1500-$3000', '9-11', 'Alert, Determined, Dignified, Friendly', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (211, 'Alapaha Blue Blood Bulldog', '$1500-$2500', '12-15', 'Protective, Trainable, Loving, Dutiful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (212, 'Alaskan Klee Kai', '$1500-$2000', '12-15', 'Active, Curious, Intelligent, Agile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (213, 'Appenzeller Sennenhund', '$1800-$2200', '12-15', 'Self-Assured, Lively, Energetic, Fearless', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (214, 'Australian Bulldog', '$2500-$3500', '10-12', 'Loyal, Familial, Loving, Easygoing', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (215, 'Australian Kelpie', '$1200-$1600', '10-14', 'Friendly, Loyal, Energetic, Eager', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (216, 'Australian Stumpy Tail Cattle Dog', '$500-$1000', '10-13', 'Devoted, Obedient, Courageous, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (217, 'Australian Black and Tan Hound', '$400-$600', '12-14', 'Good-Natured, Keen, Elegant, Agreeable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (218, 'Austrian Pinscher', '$400-$600', '12-14', 'Alert, Friendly, Devoted, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (219, 'Basset Bleu de Gascogne', '$1300-$1600', '11-13', 'Happy, Active, Curious, Agile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (220, 'Basset Fauve de Bretagne', '$1200-$1500', '11-14', 'Stubborn, Sociable, Courageous, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (221, 'Black Mouth Cur', '$500-$1300', '12-18', 'Kind, Loyal, Fearless, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (222, 'Black Norwegian Elkhound', '$700-$1000', '12-15', 'Intelligent, Alert, Strong Willed, Hardy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (223, 'Blue Lacy', '$400-$600', '14-16', 'Active, Alert, Devoted, Intense', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (224, 'Blue Pircardy Spaniel', '$900-$1200', '12-14', 'Playful, Gentle, Calm, Protective', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (225, 'Bohemian Shepherd', '$2000-$2500', '10-13', 'Active, Courageous, Trainable, Stable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (226, 'Bracco Italiano', '$2000-$2500', '11-13', 'Stubborn, Affectionate, Loyal, Companionable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (227, 'Braque du Bourbonnais', '$1200-$1500', '13-15', 'Affectionate, Kind, Calm, Cooperative', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (228, 'Brazilian Terrier', '$800-$1000', '12-14', 'Gentle, Friendly, Keen, Restless', 'True');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (229, 'Bulgarian Shepherd Dog', '$800-$1000', '12-14', 'Independent, Dominant, Brave, Proud', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (230, 'Canadian Eskimo Dog', '$3500-$8000', '12-14', 'Affectionate, Loyal, Brave, Tough', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (231, 'Carolina Dog', '$800-$1500', '12-14', 'Gentle, Loyal, Reserved, Adaptable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (232, 'Carpathian Sheepdog', '$1500-$2000', '12-14', 'Courageous, Calm, Dignified', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (233, 'Catahoula Bulldog', '$400-$700', '10-14', 'Devoted, Loyal, Companionable, Hunting Instinct', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (234, 'Catahoula Leopard Dog', '$400-$700', '11-13', 'Independent, Energetic, Inquisitive, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (235, 'Catalan Sheepdog', '$1200-$1500', '12-14', 'Intelligent, Agile, Protective, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (236, 'Caucasian Ovcharka', '$1000-$3000', '10-12', 'Quick, Calm, Dominant, Powerful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (237, 'Central Asian Ovcharka', '$1200-$2000', '12-14', 'Curious, Independent, Adaptable, Strong', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (238, 'Croatian Sheepdog', '$1000-$1200', '12-14', 'Agile, Energetic, Companionable, Keen', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (239, 'Czechoslovakian Wolfdog', '$800-$1500', '12-15', 'Sociable, Quick, Courageous, Lively', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (240, 'Dutch Shepherd Dog', '$1000-$2500', '12-15', 'Affectionate, Obedient, Loyal, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (241, 'East-European Shepherd', '$900-$1200', '12-14', 'Confident, Agile, Sensitive, Loyal', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (242, 'English Shepherd', '$400-$800', '12-15', 'Kind, Independent, Energetic, Adaptable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (243, 'Eurasier', '$2000-$2500', '11-13', 'Even Tempered, Calm, Reserved, Watchful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (244, 'Fila Brasileiro', '$1500-$2000', '9-11', 'Determined, Loyal, Obedient, Docile', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (245, 'French Spaniel', '$1500-$2000', '10-12', 'Tough, Loving, Adaptable, Energetic', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (246, 'Jagdterrier', '$700-$1000', '12-15', 'Reliable, Courageous, Sociable, Strong Willed', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (247, 'German Longhaired Pointer', '$1000-$1600', '10-12', 'Affectionate, Friendly, Kind, Familial', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (248, 'Large Munsterlander', '$1500-$1800', '11-13', 'Lively, Dependable, Trainable, Trustworthy', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (249, 'Hokkaido Dog', '$1000-$1500', '11-13', 'Alert, Dignified, Docile, Faithful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (250, 'Hovawart', '$1200-$3500', '10-14', 'Watchful, Even Tempered, Reserved, Familial', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (251, 'Korean Jindo', '$800-$1000', '12-15', 'Loyal, Brave, Active, Faithful', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (252, 'Karelian Bear Dog', '$1400-$1700', '10-12', 'Tenacious, Cautious, Loyal, Brave', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (253, 'Kishu Ken', '$1800-$2200', '11-13', 'Faithful, Docile, Noble, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (254, 'Koolie', '$700-$900', '16-18', 'Dominant, Patient, Diligent, Dedicated', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (255, 'Kromfohrlander', '$2000-$2500', '12-14', 'Docile, Spirited, Companionable, Good-Natured', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (256, 'Lancashire Heeler', '$800-$1200', '12-15', 'Clever, Friendly, Alert', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (257, 'Landseer', '$2000-$2500', '9-11', 'Generous, Courageous, Playful, Loving', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (258, 'McNab', '$700-$1000', '13-15', 'Friendly, Hard-Working, Sociable, Obedient', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (259, 'Small Munsterlander', '$1500-$1800', '12-14', 'Happy, Strong Willed, Attentive, Trainable', 'False');
INSERT INTO Dog(id,species,cost,lifespan,temper,allergyFriendly) VALUES (260, 'Norrbottenspets', '$2000-$3000', '12-15', 'Active, Attentive, Daring, Confident', 'False');
